---
# Denna fil genereras automatiskt av deploy.sh
# Ändra inte manuellt, då ändringar skrivs över.

nginx_ip: "135.225.120.91"
mariadb_ip: "10.2.1.4"
wordpress_ip: "10.2.1.6"
mongodb_ip: "10.2.1.7"
minio_ip: "10.2.1.8"
